package com.subnoize.phoenix.aws.dynamodb;

import java.time.LocalDateTime;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * 
 * @author andre
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@DynamoDBTable(tableName = "snz-products")
public class Product {

	@JsonProperty("id")
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@JsonProperty("name")
	@DynamoDBAttribute(attributeName = "name")
	private String name;

	@JsonProperty("description")
	@DynamoDBAttribute(attributeName = "description")
	private String description;

	@JsonProperty("attributes")
	@DynamoDBAttribute(attributeName = "attributes")
	private List<String> attributes;

	@JsonProperty("dateCreated")
	@DynamoDBAttribute(attributeName = "dateCreated")
	private LocalDateTime dateCreated;

	@JsonProperty("version")
	@DynamoDBVersionAttribute
	private long version;

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the attributes
	 */
	public List<String> getAttributes() {
		return attributes;
	}

	/**
	 * @param attributes the attributes to set
	 */
	public void setAttributes(List<String> attributes) {
		this.attributes = attributes;
	}

	/**
	 * @return the dateCreated
	 */
	@DynamoDBTypeConverted( converter = DynamoDBLocalDateTimeConverter.class )
	public LocalDateTime getDateCreated() {
		return dateCreated;
	}

	/**
	 * @param dateCreated the dateCreated to set
	 */
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
	public void setDateCreated(LocalDateTime dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * @return the version
	 */
	public long getVersion() {
		return version;
	}

	/**
	 * @param version the version to set
	 */
	public void setVersion(long version) {
		this.version = version;
	}

}
